In [ ]:
from google.colab import files
uploaded = files.upload()

Saving WA_Fn-UseC_-Telco-Customer-Churn.csv to WA_Fn-UseC_-Telco-Customer-Churn (3).csv

In [ ]:
import pandas as pd
import numpy as np

df=pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [ ]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [ ]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [ ]:
df.shape

(7043, 21)

In [ ]:
df.size

147903

In [ ]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [ ]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [ ]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [ ]:
df.columns = df.columns.str.strip().str.lower()

In [ ]:
df['churn'].value_counts()

churn
No     5174
Yes    1869
Name: count, dtype: int64

In [ ]:
df['churn'].value_counts(normalize=True)

churn
No     0.73463
Yes    0.26537
Name: proportion, dtype: float64

In [ ]:
# cleaning the dataset , converting totalcharges to numeric values

df['totalcharges']=pd.to_numeric(df['totalcharges'],errors='coerce')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerid        7043 non-null   object
 1   gender            7043 non-null   object
 2   seniorcitizen     7043 non-null   int64
 3   partner           7043 non-null   object
 4   dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   phoneservice      7043 non-null   object
 7   multiplelines     7043 non-null   object
 8   internetservice   7043 non-null   object
 9   onlinesecurity    7043 non-null   object
 10  onlinebackup      7043 non-null   object
 11  deviceprotection  7043 non-null   object
 12  techsupport       7043 non-null   object
 13  streamingtv       7043 non-null   object
 14  streamingmovies   7043 non-null   object
 15  contract          7043 non-null   object
 16  paperlessbilling  7043 non-null   object
 17  paymentmethod     7043 non-null   object
 18  monthlycharges    7043 non-null   float64
 19  totalcharges      7032 non-null   float64
 20  churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [ ]:
df.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

In [ ]:
#Droping the missing rows

df=df.dropna()

In [ ]:
df.shape

(7032, 21)

In [ ]:
# Encoding the target Variable
df['churn']=df['churn'].map({'Yes':1,'No':0})

In [ ]:
# feature(x) and target(y) separation
x=df.drop(['churn','customerid'],axis=1)
y=df['churn']

In [ ]:
x.columns

Index(['gender', 'seniorcitizen', 'partner', 'dependents', 'tenure',
       'phoneservice', 'multiplelines', 'internetservice', 'onlinesecurity',
       'onlinebackup', 'deviceprotection', 'techsupport', 'streamingtv',
       'streamingmovies', 'contract', 'paperlessbilling', 'paymentmethod',
       'monthlycharges', 'totalcharges'],
      dtype='object')

In [ ]:
x.shape

(7032, 19)

In [ ]:
y.name

'churn'

In [ ]:
cat_cols=x.select_dtypes(include='object').columns
num_cols=x.select_dtypes(exclude='object').columns

cat_cols,num_cols

(Index(['gender', 'partner', 'dependents', 'phoneservice', 'multiplelines',
        'internetservice', 'onlinesecurity', 'onlinebackup', 'deviceprotection',
        'techsupport', 'streamingtv', 'streamingmovies', 'contract',
        'paperlessbilling', 'paymentmethod'],
       dtype='object'),
 Index(['seniorcitizen', 'tenure', 'monthlycharges', 'totalcharges'], dtype='object'))

In [ ]:
# Train and Test Split

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

print("Shape of x_train:", x_train.shape)
print("Shape of x_test:", x_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of x_train: (5625, 19)
Shape of x_test: (1407, 19)
Shape of y_train: (5625,)
Shape of y_test: (1407,)

In [ ]:
y.value_counts(normalize=True)

churn
0    0.734215
1    0.265785
Name: proportion, dtype: float64

In [ ]:
y_train.value_counts(normalize=True)

churn
0    0.734222
1    0.265778
Name: proportion, dtype: float64

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols),
        ('num', 'passthrough', num_cols)
    ])

# x_train_encoded = preprocessor.fit_transform(x_train)
# x_test_encoded = preprocessor.transform(x_test)

# print("Shape of x_train_encoded:", x_train_encoded.shape)
# print("Shape of x_test_encoded:", x_test_encoded.shape)

In [ ]:
# Now we will create a pipeline end to end for OneHotEncoder

# one object, no leakage

from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier

In [ ]:
# pipeline = prepocessing + model together
# this avoid the mess up in order

df_pipeline=Pipeline(steps=[
    ('preprocessor',preprocessor),
    ('model',DecisionTreeClassifier(random_state=42))
])

In [ ]:
# Train the Model with decision tree

df_pipeline.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['gender', 'partner', 'dependents', 'phoneservice', 'multiplelines',
       'internetservice', 'onlinesecurity', 'onlinebackup', 'deviceprotection',
       'techsupport', 'streamingtv', 'streamingmovies', 'contract',
       'paperlessbilling', 'paymentmethod'],
      dtype='object')),
                                                 ('num', 'passthrough',
                                                  Index(['seniorcitizen', 'tenure', 'monthlycharges', 'totalcharges'], dtype='object'))])),
                ('model', DecisionTreeClassifier(random_state=42))])

In [ ]:
#Evaluating the model

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
y_pred_test=df_pipeline.predict(x_test)
print('Test accuracy_score',accuracy_score(y_test,y_pred_test))

y_pred_train=df_pipeline.predict(x_train)
print('Train accuracy_score',accuracy_score(y_train,y_pred_train))

# if train acc is high , test acc is low - overfitting
# if train acc is low , test acc is high - underfitting
# if train and test acc is high, good model and same -properfitting

Test accuracy_score 0.7221037668798863
Train accuracy_score 0.9987555555555555

In [ ]:
print(confusion_matrix(y_test,y_pred_test))

[[831 202]
 [189 185]]

In [ ]:
#classification_report
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.81      0.80      0.81      1033
           1       0.48      0.49      0.49       374

    accuracy                           0.72      1407
   macro avg       0.65      0.65      0.65      1407
weighted avg       0.73      0.72      0.72      1407

In [ ]:
for depth in [2,4,6,10,None]:
  df_pipeline=Pipeline(steps=[
    ('preprocessor',preprocessor),
    ('model',DecisionTreeClassifier(max_depth=depth,random_state=42))
  ])
  df_pipeline.fit(x_train,y_train)
  y_pred_train = df_pipeline.predict(x_train)
  train_acc = accuracy_score(y_train, y_pred_train)

  y_pred_test = df_pipeline.predict(x_test)
  test_acc = accuracy_score(y_test, y_pred_test)

  print(f'max_depth={depth}, Train={train_acc:.2f}, Test={test_acc:.2f}')

max_depth=2, Train=0.76, Test=0.75
max_depth=4, Train=0.80, Test=0.78
max_depth=6, Train=0.81, Test=0.79
max_depth=10, Train=0.87, Test=0.76
max_depth=None, Train=1.00, Test=0.72

In [ ]:
df_model=df_pipeline.named_steps['model']
encoder=df_pipeline.named_steps['preprocessor']

feature_names=encoder.get_feature_names_out()

importances=pd.Series(df_model.feature_importances_,index=feature_names)

importances.sort_values(ascending=False,inplace=True)

importances.head(10)

num__totalcharges                      0.219529
num__monthlycharges                    0.178580
cat__contract_Month-to-month           0.170143
num__tenure                            0.099469
cat__internetservice_Fiber optic       0.049254
cat__gender_Female                     0.018431
num__seniorcitizen                     0.016949
cat__onlinesecurity_No                 0.014824
cat__techsupport_No                    0.014675
cat__paymentmethod_Electronic check    0.014313
dtype: float64

In [ ]:
print(importances)

num__totalcharges                               0.219529
num__monthlycharges                             0.178580
cat__contract_Month-to-month                    0.170143
num__tenure                                     0.099469
cat__internetservice_Fiber optic                0.049254
cat__gender_Female                              0.018431
num__seniorcitizen                              0.016949
cat__onlinesecurity_No                          0.014824
cat__techsupport_No                             0.014675
cat__paymentmethod_Electronic check             0.014313
cat__gender_Male                                0.014118
cat__partner_No                                 0.013966
cat__paperlessbilling_No                        0.013845
cat__paymentmethod_Credit card (automatic)      0.013404
cat__paperlessbilling_Yes                       0.013160
cat__multiplelines_No                           0.011016
cat__streamingmovies_Yes                        0.010649
cat__onlinebackup_Yes                           0.010114
cat__deviceprotection_Yes                       0.009737
cat__dependents_No                              0.009546
cat__deviceprotection_No                        0.009446
cat__paymentmethod_Bank transfer (automatic)    0.009281
cat__onlinebackup_No                            0.008926
cat__techsupport_Yes                            0.008118
cat__paymentmethod_Mailed check                 0.007248
cat__partner_Yes                                0.006840
cat__streamingtv_No                             0.006543
cat__dependents_Yes                             0.004531
cat__multiplelines_Yes                          0.004273
cat__onlinesecurity_Yes                         0.004068
cat__contract_One year                          0.003856
cat__streamingmovies_No                         0.003386
cat__phoneservice_Yes                           0.002790
cat__phoneservice_No                            0.001372
cat__streamingtv_Yes                            0.001118
cat__streamingmovies_No internet service        0.000957
cat__multiplelines_No phone service             0.000917
cat__internetservice_DSL                        0.000610
cat__techsupport_No internet service            0.000000
cat__streamingtv_No internet service            0.000000
cat__onlinebackup_No internet service           0.000000
cat__onlinesecurity_No internet service         0.000000
cat__internetservice_No                         0.000000
cat__deviceprotection_No internet service       0.000000
cat__contract_Two year                          0.000000
dtype: float64

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf=Pipeline(steps=[
    ('preprocessor',preprocessor),
    ('model',RandomForestClassifier(n_estimators=200,random_state=42,max_depth=8,n_jobs=-1))
])

rf.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['gender', 'partner', 'dependents', 'phoneservice', 'multiplelines',
       'internetservice', 'onlinesecurity', 'onlinebackup', 'deviceprotection',
       'techsupport', 'streamingtv', 'streamingmovies', 'contract',
       'paperlessbilling', 'paymentmethod'],
      dtype='object')),
                                                 ('num', 'passthrough',
                                                  Index(['seniorcitizen', 'tenure', 'monthlycharges', 'totalcharges'], dtype='object'))])),
                ('model',
                 RandomForestClassifier(max_depth=8, n_estimators=200,
                                        n_jobs=-1, random_state=42))])

In [ ]:
y_pred_train_rf = rf.predict(x_train)
print('Train accuracy_score for Random Forest:', accuracy_score(y_train, y_pred_train_rf))

y_pred_test_rf = rf.predict(x_test)
print('Test accuracy_score for Random Forest:', accuracy_score(y_test, y_pred_test_rf))

Train accuracy_score for Random Forest: 0.8369777777777778
Test accuracy_score for Random Forest: 0.7896233120113717

In [ ]:
#Gradient Boosting

from sklearn.ensemble import GradientBoostingClassifier

gb_pipeline=Pipeline([
    ('preprocessor',preprocessor),
    ('model',GradientBoostingClassifier(n_estimators=150,random_state=42,max_depth=3,learning_rate=0.1))
])

gb_pipeline.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['gender', 'partner', 'dependents', 'phoneservice', 'multiplelines',
       'internetservice', 'onlinesecurity', 'onlinebackup', 'deviceprotection',
       'techsupport', 'streamingtv', 'streamingmovies', 'contract',
       'paperlessbilling', 'paymentmethod'],
      dtype='object')),
                                                 ('num', 'passthrough',
                                                  Index(['seniorcitizen', 'tenure', 'monthlycharges', 'totalcharges'], dtype='object'))])),
                ('model',
                 GradientBoostingClassifier(n_estimators=150,
                                            random_state=42))])

In [ ]:
y_pred_train_gb = gb_pipeline.predict(x_train)
print('Train accuracy_score for Gradient Boosting:', accuracy_score(y_train, y_pred_train_gb))

y_pred_test_gb = gb_pipeline.predict(x_test)
print('Test accuracy_score for Gradient Boosting:', accuracy_score(y_test, y_pred_test_gb))

Train accuracy_score for Gradient Boosting: 0.8424888888888888
Test accuracy_score for Gradient Boosting: 0.7867803837953091